require 'rails_helper'
require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe CourseAliasesController, type: :controller do
  before(:each){
    @admin = FactoryGirl.create(:user, :site_admin, email: 'testadmin@test.com')
    sign_in @admin
  }

  # This should return the minimal set of attributes required to create a valid
  # CourseAlias. As you add validations to CourseAlias, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }


  describe "GET #index" do
    it "assigns all course_aliases as @course_aliases" do
      course_alias = CourseAlias.create! valid_attributes
      get :index, params: {}
      expect(assigns(:course_aliases)).to eq([course_alias])
    end
  end

  describe "GET #show" do
    it "assigns the requested course_alias as @course_alias" do
      course_alias = CourseAlias.create! valid_attributes
      get :show, params: {id: course_alias.to_param}, session: valid_session
      expect(assigns(:course_alias)).to eq(course_alias)
    end
  end

  describe "GET #new" do
    it "assigns a new course_alias as @course_alias" do
      get :new, params: {}
      expect(assigns(:course_alias)).to be_a_new(CourseAlias)
    end
  end

  describe "GET #edit" do
    it "assigns the requested course_alias as @course_alias" do
      course_alias = CourseAlias.create! valid_attributes
      get :edit, params: {id: course_alias.to_param}, session: valid_session
      expect(assigns(:course_alias)).to eq(course_alias)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new CourseAlias" do
        expect {
          post :create, params: {course_alias: valid_attributes}, session: valid_session
        }.to change(CourseAlias, :count).by(1)
      end

      it "assigns a newly created course_alias as @course_alias" do
        post :create, params: {course_alias: valid_attributes}, session: valid_session
        expect(assigns(:course_alias)).to be_a(CourseAlias)
        expect(assigns(:course_alias)).to be_persisted
      end

      it "redirects to the created course_alias" do
        post :create, params: {course_alias: valid_attributes}, session: valid_session
        expect(response).to redirect_to(CourseAlias.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved course_alias as @course_alias" do
        post :create, params: {course_alias: invalid_attributes}, session: valid_session
        expect(assigns(:course_alias)).to be_a_new(CourseAlias)
      end

      it "re-renders the 'new' template" do
        post :create, params: {course_alias: invalid_attributes}, session: valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested course_alias" do
        course_alias = CourseAlias.create! valid_attributes
        put :update, params: {id: course_alias.to_param, course_alias: new_attributes}, session: valid_session
        course_alias.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested course_alias as @course_alias" do
        course_alias = CourseAlias.create! valid_attributes
        put :update, params: {id: course_alias.to_param, course_alias: valid_attributes}, session: valid_session
        expect(assigns(:course_alias)).to eq(course_alias)
      end

      it "redirects to the course_alias" do
        course_alias = CourseAlias.create! valid_attributes
        put :update, params: {id: course_alias.to_param, course_alias: valid_attributes}, session: valid_session
        expect(response).to redirect_to(course_alias)
      end
    end

    context "with invalid params" do
      it "assigns the course_alias as @course_alias" do
        course_alias = CourseAlias.create! valid_attributes
        put :update, params: {id: course_alias.to_param, course_alias: invalid_attributes}, session: valid_session
        expect(assigns(:course_alias)).to eq(course_alias)
      end

      it "re-renders the 'edit' template" do
        course_alias = CourseAlias.create! valid_attributes
        put :update, params: {id: course_alias.to_param, course_alias: invalid_attributes}, session: valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested course_alias" do
      course_alias = CourseAlias.create! valid_attributes
      expect {
        delete :destroy, params: {id: course_alias.to_param}
      }.to change(CourseAlias, :count).by(-1)
    end

    it "redirects to the course_aliases list" do
      course_alias = CourseAlias.create! valid_attributes
      delete :destroy, params: {id: course_alias.to_param}
      expect(response).to redirect_to(course_aliases_url)
    end
  end

end
